name: DamageControl
main: com.goosecraftmc.DamageControl.DamageControl
version: 0.1
author: GooseCo Inc
description: >
             Adds commands to toggle certain types of damages.
commands:
    test:
        description: DamageControl Debug Command.
    nofall:
        description: Toggles fall damage.
    nofire:
        description: Toggles fire damage.